print("계산기")
num1 = int(input("숫자1을 입력하세요"))
num2 = int(input("숫자2를 입력하세요"))
print(num1)
print(num2)
print("%d +  %d = %d" %(num1, num2, num1 + num2))
print("%d -  %d = %d" %(num1, num2, num1 - num2 ))
print("%d *  %d = %d" %(num1, num2, num1 * num2 ))
print("%d / %d = %.1f" %(num1, num2, num1 / num2 )) 
print("%d // %d = %d" %(num1, num2, num1 // num2 ))
print("%d 나머지만 구하기 %d = %d " %(num1, num2, num1 % num2 ))
